### ISSUE TITLE
Error when running EHBDroid main

### ISSUE THREAD

**Issue by louison** [wsong-nj/EHBDroid#3]
Hello there, 

I'm trying EHBDroid with the default apk openSudoku.apk. I followed instructions and loaded EHBDroid in Intellij. However, when I try to run EHBDroid, I systematically have the following error : 
```
Exception in thread "main" java.lang.ExceptionInInitializerError
	at ehb.instrumentation.FieldInstrumenter.addFieldsToActivity(FieldInstrumenter.java:30)
	at ehb.instrumentation.FieldInstrumenter.instrument(FieldInstrumenter.java:22)
	at com.app.test.AppBodyTransformer.instrumentFieldForMainActivity(AppBodyTransformer.java:80)
	at com.app.test.AppBodyTransformer.internalTransform(AppBodyTransformer.java:53)
	at soot.BodyTransformer.transform(BodyTransformer.java:51)
	at soot.Transform.apply(Transform.java:105)
	at soot.BodyPack.internalApply(BodyPack.java:49)
	at soot.Pack.apply(Pack.java:132)
	at soot.PackManager.runBodyPacks(PackManager.java:918)
	at soot.PackManager.runBodyPacks(PackManager.java:611)
	at soot.PackManager.runBodyPacks(PackManager.java:508)
	at soot.PackManager.runPacksNormally(PackManager.java:485)
	at soot.PackManager.runPacks(PackManager.java:392)
	at soot.Main.run(Main.java:271)
	at soot.Main.main(Main.java:147)
	at com.app.test.AndroidInstrumentor.transform(AndroidInstrumentor.java:14)
	at com.app.test.AndroidInstrumentor.instrument(AndroidInstrumentor.java:8)
	at com.app.test.Main.instrumentApp(Main.java:136)
	at com.app.test.Main.parseJavaCode(Main.java:71)
	at com.app.test.Main.main(Main.java:48)
Caused by: java.lang.RuntimeException: tried to get nonexistent method <com.app.test.Util: void LogException(java.lang.Exception)>
	at soot.Scene.getMethod(Scene.java:652)
	at com.app.test.Constants.<clinit>(Constants.java:104)
```

It seems that the program is not able to find the method <com.app.test.Util: void LogException(java.lang.Exception)> in your Util class. 

Do you know how I can fix that ? 
Thank you in advance !

**Comment by Xiangxingqian** [comment]
Hi LouisonGitzinger,

In Intellij, please change statement in  `com.app.test.Main#initSoot(String[] args)`

```
Options.v().set_soot_classpath(args[3] + ":" + "lib/rt.jar:" + "lib/jce.jar:" + "lib/tools.jar:"
	+ "lib/android.jar:" + "lib/android-support-v4.jar:" + "bin"); 
```

to

```
Options.v().set_soot_classpath(apkPath + ":" + "lib/rt.jar:" + "lib/jce.jar:" + "lib/tools.jar:"
                + "lib/android.jar:" + "lib/android-support-v4.jar:" + "out/production/EHBDroid");
```

It should work.

**Comment by louison** [comment]
Hi there, 
Using this : 
```java
String apkPath = "/Users/lgitzing/Development/EHBDroid/EHBDroid/benchmark/OpenSudoku.apk";
Options.v().set_soot_classpath(apkPath + ":" + "lib/rt.jar:" + "lib/jce.jar:" + "lib/tools.jar:"
				+ "lib/android.jar:" + "lib/android-support-v4.jar:" + "out/production/EHBDroid");
```

I still have the same error : 
```java
Exception in thread "main" java.lang.ExceptionInInitializerError
	at ehb.instrumentation.FieldInstrumenter.addFieldsToActivity(FieldInstrumenter.java:30)
	at ehb.instrumentation.FieldInstrumenter.instrument(FieldInstrumenter.java:22)
	at com.app.test.AppBodyTransformer.instrumentFieldForMainActivity(AppBodyTransformer.java:80)
	at com.app.test.AppBodyTransformer.internalTransform(AppBodyTransformer.java:53)
	at soot.BodyTransformer.transform(BodyTransformer.java:51)
	at soot.Transform.apply(Transform.java:105)
	at soot.BodyPack.internalApply(BodyPack.java:49)
	at soot.Pack.apply(Pack.java:132)
	at soot.PackManager.runBodyPacks(PackManager.java:918)
	at soot.PackManager.runBodyPacks(PackManager.java:611)
	at soot.PackManager.runBodyPacks(PackManager.java:508)
	at soot.PackManager.runPacksNormally(PackManager.java:485)
	at soot.PackManager.runPacks(PackManager.java:392)
	at soot.Main.run(Main.java:271)
	at soot.Main.main(Main.java:147)
	at com.app.test.AndroidInstrumentor.transform(AndroidInstrumentor.java:14)
	at com.app.test.AndroidInstrumentor.instrument(AndroidInstrumentor.java:8)
	at com.app.test.Main.instrumentApp(Main.java:141)
	at com.app.test.Main.parseJavaCode(Main.java:71)
	at com.app.test.Main.main(Main.java:48)
Caused by: java.lang.RuntimeException: tried to get nonexistent method <android.app.ListActivity: void onListItemClick(android.widget.ListView,android.view.View,int,long)>
	at soot.Scene.getMethod(Scene.java:652)
	at com.app.test.Constants.<clinit>(Constants.java:53)
	... 20 more
```

Any Suggestion ?

**Comment by docsnyder12345** [comment]
I´ve got the same Error when tinkering with EHBDroid (under Windows), also he gives a few Warnings in the beginning : 

```[main] WARN ehb.analysis.entryPointCreator.AndroidEntryPointCreator - Cannot create valid constructor for android.view.Menu, because it is an interface and cannot substitute with subclass
[main] WARN ehb.analysis.entryPointCreator.AndroidEntryPointCreator - Cannot create valid constructor for android.view.MenuItem, because it is an interface and cannot substitute with subclass
[main] WARN ehb.analysis.entryPointCreator.AndroidEntryPointCreator - Cannot create valid constructor for android.content.Context, because it is abstract and cannot substitute with subclass
[main] WARN ehb.analysis.entryPointCreator.AndroidEntryPointCreator - Cannot create valid constructor for android.view.ContextMenu, because it is an interface and cannot substitute with subclass
[main] WARN ehb.analysis.entryPointCreator.AndroidEntryPointCreator - Cannot create valid constructor for android.view.ContextMenu$ContextMenuInfo, because it is an interface and cannot substitute with subclass
```
As well as : 

```
Exception in thread "main" java.lang.ExceptionInInitializerError
	at ehb.instrumentation.FieldInstrumenter.addFieldsToActivity(FieldInstrumenter.java:30)
	at ehb.instrumentation.FieldInstrumenter.instrument(FieldInstrumenter.java:22)
	at com.app.test.AppBodyTransformer.instrumentFieldForMainActivity(AppBodyTransformer.java:80)
	at com.app.test.AppBodyTransformer.internalTransform(AppBodyTransformer.java:53)
	at soot.BodyTransformer.transform(BodyTransformer.java:51)
	at soot.Transform.apply(Transform.java:105)
	at soot.BodyPack.internalApply(BodyPack.java:49)
	at soot.Pack.apply(Pack.java:132)
	at soot.PackManager.runBodyPacks(PackManager.java:918)
	at soot.PackManager.runBodyPacks(PackManager.java:611)
	at soot.PackManager.runBodyPacks(PackManager.java:508)
	at soot.PackManager.runPacksNormally(PackManager.java:485)
	at soot.PackManager.runPacks(PackManager.java:392)
	at soot.Main.run(Main.java:271)
	at soot.Main.main(Main.java:147)
	at com.app.test.AndroidInstrumentor.transform(AndroidInstrumentor.java:14)
	at com.app.test.AndroidInstrumentor.instrument(AndroidInstrumentor.java:8)
	at com.app.test.Main.instrumentApp(Main.java:136)
	at com.app.test.Main.parseJavaCode(Main.java:71)
	at com.app.test.Main.main(Main.java:47)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.intellij.rt.execution.application.AppMainV2.main(AppMainV2.java:131)
Caused by: java.lang.RuntimeException: tried to get nonexistent method <com.app.test.Util: void LogException(java.lang.Exception)>
	at soot.Scene.getMethod(Scene.java:652)
	at com.app.test.Constants.<clinit>(Constants.java:104)
	... 25 more

Process finished with exit code 1
```

Any Quick Solution in Sight?

**Comment by docsnyder12345** [comment]
Okay, now so i set up Java SDK 9 (and changed the Encoding Settings in IntelliJ because it threw some Errors after reinstalling) and the above Errors have disappeared, but now i get a NullPointer : 

```
Exception in thread "main" java.lang.NullPointerException
	at soot.JastAddJ.Program.initPaths(Program.java:350)
	at soot.SootResolver.<init>(SootResolver.java:88)
	at soot.Singletons.soot_SootResolver(Singletons.java:808)
	at soot.SootResolver.v(SootResolver.java:93)
	at soot.Scene.forceResolve(Scene.java:1575)
	at ehb.analysis.entryPointCreator.AndroidEntryPointCreator.createDummyMainInternal(AndroidEntryPointCreator.java:177)
	at ehb.analysis.entryPointCreator.BaseEntryPointCreator.createDummyMain(BaseEntryPointCreator.java:83)
	at ehb.analysis.entryPointCreator.AndroidEntryPointCreator.createDummyMain(AndroidEntryPointCreator.java:140)
	at ehb.analysis.CallGraphBuilder.buildDummyMainMethod(CallGraphBuilder.java:155)
	at ehb.analysis.CallGraphBuilder.initSoot(CallGraphBuilder.java:130)
	at ehb.analysis.CallGraphBuilder.build(CallGraphBuilder.java:179)
	at com.app.test.Main.parseJavaCode(Main.java:67)
	at com.app.test.Main.main(Main.java:47)
```

Any Solution to that?

**Comment by sangamk** [comment]
Forr anyone stuck here on Windows. Change sdk to 1.8 (JAVA 8) because System.getProperty("sun.boot.class.path") is removed in Java 9. Also use ";" instead of ":". And make sure your path is correct.

**Comment by sangamk** [comment]
@docsnyder12345 Did you manage to find a solution? The last error is because System.getProperty("sun.boot.class.path") is removed in Java 9.

**Comment by docsnyder12345** [comment]
@sangamk I didn´t investigate it any further because my Time didn´t allow it.
But if the last Error i got is fixed with changing to Java SDK 8 then it should be working.

**Comment by sangamk** [comment]
@docsnyder12345 Unfortunately that just gives me the first error again. There is another repository made by the same author called codecoveragetool which is just a subset of this. There I did manage to get an instrumented apk. The same does not seem to work for this repository.

**Comment by zmqgeek** [comment]
I also encountered the same problem, how to solved it?The solution you mentioned does not work. @Xiangxingqian
