### ISSUE TITLE
Fail to run Main.java

### ISSUE THREAD

**Issue by tykuyh** [wsong-nj/EHBDroid#6]
I have import the project in IDEA as the eclipse project 
but when I run the Main.java, it failed.
I don't changed any code and run it directly.
The log is:

[main] WARN ehb.analysis.entryPointCreator.AndroidEntryPointCreator - Cannot create valid constructor for android.view.Menu, because it is an interface and cannot substitute with subclass
[main] WARN ehb.analysis.entryPointCreator.AndroidEntryPointCreator - Cannot create valid constructor for android.view.MenuItem, because it is an interface and cannot substitute with subclass
[main] WARN ehb.analysis.entryPointCreator.AndroidEntryPointCreator - Cannot create valid constructor for android.content.Context, because it is abstract and cannot substitute with subclass
[main] WARN ehb.analysis.entryPointCreator.AndroidEntryPointCreator - Cannot create valid constructor for android.view.ContextMenu, because it is an interface and cannot substitute with subclass
[main] WARN ehb.analysis.entryPointCreator.AndroidEntryPointCreator - Cannot create valid constructor for android.view.ContextMenu$ContextMenuInfo, because it is an interface and cannot substitute with subclass
Warning: com.app.test.event.InterAppEvent is a phantom class!
Warning: ehb.instrumentation.codecoverage.CoverageToolkit is a phantom class!
Warning: com.app.test.data.PatternMatcher is a phantom class!
Warning: com.app.test.event.SystemEventConstants is a phantom class!
Warning: com.app.test.AppDir is a phantom class!
Warning: com.app.test.CallBack is a phantom class!
Warning: com.app.test.event.SystemEventHandler is a phantom class!
Warning: com.app.test.data.AndroidIntentFilter is a phantom class!
Warning: com.app.test.constant.EHBClass is a phantom class!
Warning: com.app.test.event.ReceiverEvent is a phantom class!
Warning: com.app.test.data.AndroidIntentFilter$AuthorityEntry is a phantom class!
Warning: com.app.test.event.SystemEvent is a phantom class!
Warning: com.app.test.constant.LogTag is a phantom class!
Warning: com.app.test.constant.EHBMethod is a phantom class!
Warning: com.app.test.event.UIEvent is a phantom class!
Warning: com.app.test.event.SystemEventHandler$1 is a phantom class!
Warning: com.app.test.event.InterAppEventHandler is a phantom class!
Warning: com.app.test.event.UIEventHandler$1 is a phantom class!
Warning: com.app.test.Util is a phantom class!
Warning: com.app.test.constant.EHBField is a phantom class!
Warning: com.app.test.event.InterAppEventHandler$1 is a phantom class!
Warning: com.app.test.event.UIEventHandler is a phantom class!
Warning: com.app.test.event.UIEventHandler$UIEventTesterForSeq is a phantom class!
Warning: java.lang.invoke.LambdaMetafactory is a phantom class!
Exception in thread "main" soot.CompilationDeathException: Couldn't resolve classpath entry benchmark/OpenSudoku.apk:lib/rt.jar:lib/jce.jar:lib/tools.jar:lib/android.jar:lib/android-support-v4.jar:bin: java.io.IOException: 文件名、目录名或卷标语法不正确。
	at soot.SourceLocator.explodeClassPath(SourceLocator.java:491)
	at soot.SourceLocator.getClassSource(SourceLocator.java:67)
	at soot.SootResolver.bringToHierarchy(SootResolver.java:209)
	at soot.SootResolver.bringToSignatures(SootResolver.java:266)
	at soot.SootResolver.bringToBodies(SootResolver.java:304)
	at soot.SootResolver.processResolveWorklist(SootResolver.java:167)
	at soot.SootResolver.resolveClass(SootResolver.java:131)
	at soot.Scene.tryLoadClass(Scene.java:675)
	at soot.Scene.loadBasicClasses(Scene.java:1272)
	at soot.Scene.loadNecessaryClasses(Scene.java:1351)
	at com.app.test.Main.initSoot(Main.java:99)
	at com.app.test.Main.parseJavaCode(Main.java:70)
	at com.app.test.Main.main(Main.java:48)

Process finished with exit code 1

Using the jdk8, and really don't why it happened.

**Comment by zmqgeek** [comment]
I have the same problem，can you slove it? @tykuyh

**Comment by tykuyh** [comment]
@zmqgeek 之后没有继续研究，但我觉得可能是classpath有一些还需要修改吧

**Comment by jlewis39** [comment]
@zmqgeek Were you able to solve this error?

**Comment by DGHSRailgun** [comment]
> ca

I fixed this bug in the Windows . First you need to change the initSoot() method in the Main class(the same to your operating system). Then if it still doesn' work, find out CallGraphBuilder.java and change the initSoot() set_soot_classpath. It works well on my windows 10 right now with different apps.

**Comment by DGHSRailgun** [comment]
I fixed this bug in the Windows . First you need to change the initSoot() method in the Main class(the same to your operating system). Then if it still doesn' work, find out CallGraphBuilder.java and change the initSoot() set_soot_classpath. It works well on my windows 10 right now with different apps.

**Comment by DGHSRailgun** [comment]
I fixed this bug on the Windows . First you need to change the initSoot() method in the Main class(the same to your operating system). Then if it still doesn' work, find out CallGraphBuilder.java and change the initSoot() set_soot_classpath. It works well on my windows 10 right now with different apps.
